name: bullbearnews
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.6.1 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.0
  firebase_auth: ^5.5.0
  cloud_firestore: ^5.6.4
  firebase_messaging: ^15.2.3
  provider: ^6.1.4
  http: ^1.3.0
  flutter_dotenv: ^5.2.1
  shared_preferences: ^2.5.2
  cached_network_image: ^3.4.1
  share_plus: ^10.1.4
  cloudinary_public: ^0.23.1
  image_picker: ^1.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  webview_flutter: ^4.10.0
  webview_flutter_wkwebview: ^3.18.5
  fl_chart: ^0.70.2
  emoji_picker_flutter: ^4.3.0
  youtube_player_flutter: ^9.1.1
  connectivity_plus: ^6.1.3
  fluttertoast: ^8.2.12
  shimmer: ^3.0.0
  dio: ^5.8.0+1
  flutter_cache_manager: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  hive_generator: ^2.0.1
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/moon.png
    - assets/icons/sun.png

  fonts:
    - family: Mono
      fonts:
        - asset: assets/fonts/Monomakh-Regular.ttf

    - family: Barlow
      fonts:
        - asset: assets/fonts/BarlowCondensed-Regular.ttf

    - family: DMSerif
      fonts:
        - asset: assets/fonts/DMSerifText-Regular.ttf
