// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4Ctku43bicOCBN4QXXvPXEjWJUNsp25k',
    appId: '1:211885957058:web:77687c09d9925b9e87405b',
    messagingSenderId: '211885957058',
    projectId: 'bullbearnews-4eff4',
    authDomain: 'bullbearnews-4eff4.firebaseapp.com',
    storageBucket: 'bullbearnews-4eff4.firebasestorage.app',
    measurementId: 'G-61J961L6H5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3QoDXsOi3CQTOGi6LaSMautk6NzWki-g',
    appId: '1:211885957058:android:7727fbf566e4ff9d87405b',
    messagingSenderId: '211885957058',
    projectId: 'bullbearnews-4eff4',
    storageBucket: 'bullbearnews-4eff4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALWWvzCFbd1Grk_42bkaCGLgO_8K2JMzo',
    appId: '1:211885957058:ios:afd427be6bf4730387405b',
    messagingSenderId: '211885957058',
    projectId: 'bullbearnews-4eff4',
    storageBucket: 'bullbearnews-4eff4.firebasestorage.app',
    iosBundleId: 'com.example.bullbearnews',
  );
}
